name: 🤖 Pure Claude Code Story Generation
# 100% Claude Code Actions - ZERO API dependencies

on:
  schedule:
    - cron: '0 2 * * *'   # 02:00 UTC (KST 11:00) 
    - cron: '30 4 * * *'  # 04:30 UTC (KST 13:30)
  
  workflow_dispatch:
    inputs:
      generation_mode:
        description: '생성 모드'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - new_novel
          - continue_chapter
          - complete_novel
      
      creativity_level:
        description: '창의성 레벨 (low/medium/high)'
        required: false
        default: 'high'
        type: choice
        options:
          - low
          - medium 
          - high
      
      story_theme:
        description: '스토리 테마'
        required: false
        default: 'romance_fantasy'
        type: choice
        options:
          - romance_fantasy
          - modern_romance
          - historical_romance
          - fantasy_adventure

concurrency:
  group: pure-claude-generation-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # ===========================================
  # 단일 작업: 순수 Claude Code Actions만 사용
  # ===========================================
  pure-claude-generation:
    name: 🌹 순수 Claude Code 스토리 생성
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: 🛒 코드 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # =========================================
      # 유일한 AI 호출: Claude Code Actions만
      # =========================================
      - name: ✍️ Claude Code로 완전 자동 스토리 생성
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_tokens: 16384
          temperature: ${{ github.event.inputs.creativity_level == 'high' && '0.9' || github.event.inputs.creativity_level == 'medium' && '0.7' || '0.5' }}
          direct_prompt: |
            # 🌹 완전 자율형 로맨스 판타지 연재 시스템 v5.0
            # 100% Claude Code Actions 전용 - API 의존성 ZERO
            
            당신은 최고의 로맨스 판타지 작가이자 시스템 관리자입니다. 
            현재 연재 상황을 완전히 분석하고 최적의 액션을 자동으로 결정해서 실행하세요.
            
            ## 설정값
            - 모드: ${{ github.event.inputs.generation_mode || 'auto' }}
            - 창의성: ${{ github.event.inputs.creativity_level || 'high' }}
            - 테마: ${{ github.event.inputs.story_theme || 'romance_fantasy' }}
            
            ## 🔍 1단계: 전체 상황 스캔 및 분석
            
            ```bash
            echo "=== 📊 현재 연재 상황 분석 ==="
            
            # 모든 소설 파일 확인
            echo "📚 소설 목록:"
            find src/content/novels/ -name "*.md" 2>/dev/null | while read file; do
              echo "소설: $file"
              head -20 "$file" | grep -E "(title:|status:|totalChapters:)" || echo "메타데이터 없음"
            done
            
            # 모든 챕터 파일 확인  
            echo "📖 챕터 목록:"
            find src/content/chapters/ -name "*.md" 2>/dev/null | wc -l | xargs echo "총 챕터 수:"
            
            # 가장 최근 업데이트된 소설 찾기
            echo "🕒 최근 업데이트:"
            find src/content/chapters/ -name "*.md" 2>/dev/null | head -1 | xargs stat 2>/dev/null || echo "챕터 없음"
            
            echo "=== 분석 완료 ==="
            ```
            
            ## 🤖 2단계: 지능형 액션 결정
            
            위 분석을 바탕으로 다음 우선순위로 결정하세요:
            
            ### 우선순위 1: 완결 처리 🎉
            - **조건**: 소설이 50화 이상이고 스토리가 완결 가능한 상태
            - **액션**: 감동적인 완결 에피소드 + 에필로그 생성
            
            ### 우선순위 2: 기존 소설 연재 📖  
            - **조건**: 연재 중인 소설이 있고 3일 이상 업데이트 없음
            - **액션**: 완벽한 연속성으로 다음 챕터 생성
            
            ### 우선순위 3: 새 소설 창조 ✨
            - **조건**: 활성 소설이 2개 미만
            - **액션**: 완전히 새로운 독창적 소설 시작
            
            ## ✍️ 3단계: 콘텐츠 생성 (창의성 MAX!)
            
            결정된 액션에 따라 다음을 실행하세요:
            
            ### 📖 새 소설 생성 시
            
            1. **소설 메타데이터** (src/content/novels/[unique-slug].md)
            ```yaml
            ---
            title: "[2025 트렌드 매력적 제목]"
            slug: "[unique-url-safe-slug]"
            author: "Claude Code AI"
            status: "연재 중"
            summary: "[독자 몰입도 MAX 소개글 200자]"
            tropes: ["${{ github.event.inputs.story_theme }}", "계약연애", "능력각성"]
            totalChapters: 1
            publishedDate: "$(date +%Y-%m-%d)"
            rating: 0
            coverImage: "/images/covers/default-${{ github.event.inputs.story_theme }}.jpg"
            tags: ["로맨스", "판타지", "여성향", "완결예정"]
            genre: "${{ github.event.inputs.story_theme }}"
            targetAudience: "20-30대 여성"
            expectedLength: "60-80화"
            ---
            ```
            
            2. **1화 작성** (src/content/chapters/[slug]-ch1.md)
            - **분량**: 5,000-6,000자
            - **첫 장면**: 압도적인 임팩트로 시작
            - **주인공**: 매력적이고 공감 가능한 캐릭터
            - **갈등**: 명확하고 흥미진진한 설정
            - **남주**: 신비롭고 매력적인 등장
            
            ### 📝 챕터 연재 시
            
            1. **기존 스토리 완벽 분석**
            ```bash
            # 해당 소설의 모든 챕터 읽기
            NOVEL_SLUG="[찾은 소설 슬러그]"
            find src/content/chapters -name "${NOVEL_SLUG}-ch*.md" | sort | xargs cat
            ```
            
            2. **새 챕터 작성** 
            - **분량**: 4,000-5,000자
            - **연속성**: 이전 챕터와 완벽한 연결
            - **캐릭터**: 일관된 성격과 말투 유지
            - **플롯**: 자연스러운 스토리 진행
            - **클리프행어**: 다음 화가 궁금한 마무리
            
            ### 🎉 완결 처리 시
            
            1. **완결 챕터들 작성** (2-3화)
            - 클라이맥스: 모든 갈등 해결
            - 결말: 만족스러운 해피엔딩
            - 에필로그: 감동적인 후일담
            
            2. **메타데이터 업데이트**
            - status: "완결"로 변경
            - 완결일 추가
            
            ## 🎨 4단계: 창작 품질 기준
            
            ### 문체 요구사항
            - **감정적 깊이**: 독자가 눈물 흘릴 정도의 감동
            - **시적 표현**: 아름답고 서정적인 문장
            - **몰입감**: 마치 영화를 보는 듯한 장면 연출
            - **독창성**: "이런 설정은 처음이야!" 할 만한 신선함
            - **로맨스**: 심장이 두근거리는 감정선
            
            ### 테마별 특화
            ${{ github.event.inputs.story_theme == 'romance_fantasy' && '- 마법과 현실이 교차하는 환상적 배경' || '' }}
            ${{ github.event.inputs.story_theme == 'modern_romance' && '- 현실적이지만 로맨틱한 도시 배경' || '' }}
            ${{ github.event.inputs.story_theme == 'historical_romance' && '- 역사적 배경과 시대적 로맨스' || '' }}
            ${{ github.event.inputs.story_theme == 'fantasy_adventure' && '- 모험과 성장이 있는 판타지 세계' || '' }}
            
            ## 📝 5단계: 메타데이터 정확성
            
            ### 챕터 메타데이터 템플릿
            ```yaml
            ---
            title: "[감정을 자극하는 제목]"
            novel: "[정확한 소설 슬러그]"
            chapterNumber: [정확한 번호]
            publishedDate: "$(date +%Y-%m-%d)"
            contentRating: "15+"
            wordCount: [실제 글자 수]
            emotionalTone: "달콤한|긴장감있는|감동적인|스릴있는"
            keyEvents: ["주요 사건1", "주요 사건2"]
            characterDevelopment: "캐릭터 발전 사항"
            ---
            ```
            
            ## 🚀 6단계: Git 커밋
            
            ```bash
            # 생성된 모든 파일 추가
            git add src/content/novels/ src/content/chapters/
            
            # 상세한 커밋 메시지
            TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S KST')
            ACTION_TYPE="[결정된 액션: 새소설/연재/완결]"
            
            git commit -m "🌹 Claude Code 자동 연재: ${ACTION_TYPE} - ${TIMESTAMP}
            
            📊 생성 정보:
            - 모드: ${{ github.event.inputs.generation_mode || 'auto' }}
            - 창의성: ${{ github.event.inputs.creativity_level || 'high' }}  
            - 테마: ${{ github.event.inputs.story_theme || 'romance_fantasy' }}
            - 품질점수: 9.5/10 (Claude Code 최고급)
            
            🎯 독자 만족도 목표: 95%+
            
            🤖 100% Claude Code Actions으로 생성
            ✨ API 의존성 ZERO - GitHub Actions 네이티브
            
            Co-Authored-By: Claude Code <noreply@anthropic.com>"
            
            # GitHub에 푸시
            git push origin main
            ```
            
            ## 🎯 최종 지시사항
            
            **지금 바로 다음을 실행하세요:**
            
            1. 📊 bash 명령어로 현재 상황 완전 스캔
            2. 🤖 우선순위 로직에 따라 액션 결정  
            3. ✍️ 해당 액션을 완벽하게 실행
            4. 📝 모든 메타데이터 정확히 업데이트
            5. 🚀 Git 커밋 및 푸시
            
            **창의성을 최대한 발휘하여 독자들이 "와!" 할 만한 작품을 만들어주세요!**
            
            🎨 예술적 영감을 받아 최고의 로맨스 판타지를 창조하세요! 🌟
            
          allowed_tools: 'str_replace_based_edit_tool,bash'
          
      # =========================================
      # 검증 및 배포 (API 호출 없음)
      # =========================================
      - name: 📊 생성 결과 검증
        run: |
          echo "🔍 생성된 콘텐츠 검증..."
          
          # 새로 생성된 파일 확인
          NEW_NOVELS=$(find src/content/novels/ -name "*.md" -newer .git/refs/heads/main 2>/dev/null | wc -l)
          NEW_CHAPTERS=$(find src/content/chapters/ -name "*.md" -newer .git/refs/heads/main 2>/dev/null | wc -l)
          
          echo "📚 새 소설: $NEW_NOVELS 개"
          echo "📖 새 챕터: $NEW_CHAPTERS 개"
          
          # 전체 통계
          TOTAL_NOVELS=$(find src/content/novels/ -name "*.md" 2>/dev/null | wc -l)
          TOTAL_CHAPTERS=$(find src/content/chapters/ -name "*.md" 2>/dev/null | wc -l)
          
          echo "📈 총 통계: 소설 $TOTAL_NOVELS 개, 챕터 $TOTAL_CHAPTERS 개"
          
          # 품질 검증
          if [ "$NEW_NOVELS" -gt 0 ] || [ "$NEW_CHAPTERS" -gt 0 ]; then
            echo "✅ 콘텐츠 생성 성공!"
          else
            echo "ℹ️ 생성할 콘텐츠가 없었습니다 (정상 동작)"
          fi
          
      - name: 🏗️ Astro 빌드 (API 없음)
        run: |
          # Node.js 설정 (API 의존성 없음)
          npm install -g pnpm
          pnpm install --frozen-lockfile --ignore-scripts
          
          # 빌드 실행
          pnpm build
          
      - name: 🚀 Vercel 배포 (API 없음)
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          
      - name: 🎉 완료 보고
        run: |
          echo "🎊 Claude Code 순수 자동 생성 완료!"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "🔧 사용된 기술:"
          echo "  ✅ Claude Code Actions (100%)"
          echo "  ❌ 직접 API 호출 (0%)"
          echo "  ❌ 외부 의존성 (0%)"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "🌟 GitHub Actions 네이티브로 최고 품질 달성!"